### ISSUE TITLE
How can I make the <head> section different for different pages because of SEO? 

### ISSUE THREAD

**Issue by saeedhei** [keithweaver/MERN-boilerplate#10]
How can I make the <head> section different for different pages because of SEO? 
**Head of page A:**
`<meta name="robots" content="noindex, nofollow">`
**Head of Page B:**
`<meta name="robots" content="index, follow">`

**Comment by lastgiven** [comment]
You can use react-helmet for this.

**Comment by saeedhei** [comment]
Thanks you
